(() => {
  const state = { faction: 'shu', cards: [], owned: [], saved: [], deck: new Map(), editing: null, typeFilter: '', costFilter: null };
  const $ = (id) => document.getElementById(id);
  const typeName = { troop: '兵种', general: '武将', strategist: '谋臣', tactic: '战法', event: '事件' };
  const factionName = { shu: '蜀', wei: '魏', wu: '吴', qun: '群', neutral: '中立' };
  const api = async (path, options) => { const r = await fetch(path, options); const body = await r.json(); if (!r.ok) throw new Error(body.error || '请求失败'); return body; };
  const html = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const card = (id) => state.owned.find((x) => x.id === id);
  function effectText(c) { const texts = (c.skills || []).map((s) => s.text || s.name).filter(Boolean); if (texts.length) return texts.join('；'); if ((c.keywords || []).length) return `关键词：${c.keywords.join('、')}`; return c.memo || '暂无效果描述'; }
  function renderFilters() { const types = [['', '全部'], ['troop', '兵种'], ['general', '武将'], ['strategist', '谋臣'], ['tactic', '战法'], ['event', '事件']]; $('type-filters').innerHTML = types.map(([v, label]) => `<button class="${state.typeFilter === v ? 'active' : ''}" data-type-filter="${v}">${label}</button>`).join(''); const costs = [null, 0, 1, 2, 3, 4, 5, 6, 7, 8]; $('cost-filters').innerHTML = costs.map((v) => `<button class="${state.costFilter === v ? 'active' : ''}" data-cost-filter="${v === null ? 'all' : v}">${v === null ? '全部' : `${v}费`}</button>`).join(''); }
  function renderCards() { const search = $('search').value.toLowerCase(); const total = [...state.deck.values()].reduce((a, b) => a + b, 0); $('cards').innerHTML = state.owned.filter((c) => (!state.typeFilter || c.type === state.typeFilter) && (state.costFilter === null || c.cost === state.costFilter) && (!search || `${c.id} ${c.name}`.toLowerCase().includes(search))).map((c) => { const n = state.deck.get(c.id) || 0; const max = c.type === 'troop' ? 3 : 1; const disabled = n >= Math.min(max, c.owned) || total >= 30; const stats = c.attack != null && c.health != null ? `<div class="stats" aria-label="攻击 ${c.attack}，生命 ${c.health}"><span class="stat attack">攻 ${c.attack}</span><span class="stat health">血 ${c.health}</span></div>` : ''; return `<article class="card ${c.implemented ? '' : 'off'}"><div class="cardhead"><span class="name">${c.name}</span><span>${c.cost}费</span></div><div class="card-tags"><span class="card-tag faction">${factionName[c.faction] || c.faction}</span><span class="card-tag">${typeName[c.type] || c.type}</span></div><div class="card-details"><div class="desc">${effectText(c)}</div>${stats}</div><div class="cardfoot"><span class="owned">拥有 ${c.owned} 张 · 当前 ${n}/${max}</span><button data-add="${c.id}" ${disabled ? 'disabled' : ''}>${n >= Math.min(max, c.owned) ? '已满' : (total >= 30 ? '卡组满' : '加入')}</button></div></article>`; }).join('') || '<div class="empty">当前阵营没有符合条件的卡牌</div>'; }
  function renderDeck() { const entries = [...state.deck.entries()]; const total = entries.reduce((n, [, q]) => n + q, 0); $('count').textContent = `${total} / 30`; $('deck').innerHTML = entries.map(([id, q]) => { const c = card(id); return `<div class="deckrow"><span><b>${c.name}</b><small class="deck-card-info"> ${c.cost}费 · ${factionName[c.faction] || c.faction} · ${typeName[c.type] || c.type}</small></span><span class="actions"><button data-minus="${id}">−</button> ${q} <button data-plus="${id}">+</button></span></div>`; }).join('') || '<div class="empty">点击左侧卡牌加入卡组</div>'; $('summary').textContent = total === 30 ? '卡组数量合法；保存时服务端会再次校验阵营、收藏和同名上限。' : `还需要 ${30 - total} 张卡牌。`; }
  function render() { renderFilters(); renderCards(); renderDeck(); }
  async function loadCards() { const body = await api(`/api/users/demo-user/cards?faction=${state.faction}`); state.owned = body.cards.filter((c) => c.implemented); render(); }
  async function loadSaved() { const body = await api('/api/users/demo-user/decks'); state.saved = body.decks; $('saved').innerHTML = `<h2>已保存卡组</h2>` + (state.saved.map((d) => `<div class="savedrow"><span class="saved-name">${html(d.name)} · ${factionName[d.faction] || d.faction} · ${d.revision}版</span><span class="saved-actions"><button data-load="${d.id}">载入</button><button class="danger" data-delete="${d.id}">删除</button></span></div>`).join('') || '<div class="empty">还没有保存的卡组</div>'); }
  async function loadDeck(id) { const d = await api(`/api/users/demo-user/decks/${id}`); state.editing = d.id; state.faction = d.faction; $('faction').value = d.faction; $('deck-name').value = d.name; state.deck = new Map(d.cards.map((x) => [x.cardId, x.quantity])); await loadCards(); }
  async function deleteDeck(id, name) { if (!confirm(`确定删除卡组“${name}”吗？此操作无法撤销。`)) return; await api(`/api/users/demo-user/decks/${id}`, { method: 'DELETE' }); if (state.editing === id) { state.editing = null; state.deck.clear(); $('deck-name').value = '我的卡组'; render(); } setStatus(`已删除卡组“${name}”`); await loadSaved(); }
  function setStatus(message, bad = false) { $('status').textContent = message; $('status').className = bad ? 'notice bad' : 'notice ok'; }
  function installFilters() { const type = $('type'); type.outerHTML = '<div class="filter-row"><span class="filter-label">类型</span><div id="type-filters" class="filter-buttons"></div></div><div class="filter-row"><span class="filter-label">费用</span><div id="cost-filters" class="filter-buttons"></div></div>'; const style = document.createElement('style'); style.textContent = '.filter-row{display:flex;align-items:flex-start;gap:8px;margin:0 0 8px}.filter-label{flex:0 0 34px;color:var(--muted);font-size:12px;padding:6px 0}.filter-buttons{display:flex;gap:5px;flex-wrap:wrap}.filter-buttons button{padding:5px 9px;font-size:12px}.filter-buttons button.active{background:var(--gold);border-color:#bd9855;color:#241c10;font-weight:700}'; document.head.appendChild(style); }
  $('faction').addEventListener('change', async (e) => { state.faction = e.target.value; state.deck.clear(); state.editing = null; await loadCards(); }); $('search').addEventListener('input', renderCards); installFilters();
  $('type-filters').addEventListener('click', (e) => { if (e.target.dataset.typeFilter !== undefined) { state.typeFilter = e.target.dataset.typeFilter; render(); } }); $('cost-filters').addEventListener('click', (e) => { if (e.target.dataset.costFilter !== undefined) { state.costFilter = e.target.dataset.costFilter === 'all' ? null : Number(e.target.dataset.costFilter); render(); } });
  $('cards').addEventListener('click', (e) => { const id = e.target.dataset.add; if (!id) return; const c = card(id); const max = c.type === 'troop' ? 3 : 1; const n = state.deck.get(id) || 0; if (n < Math.min(max, c.owned) && [...state.deck.values()].reduce((a, b) => a + b, 0) < 30) state.deck.set(id, n + 1); render(); });
  $('deck').addEventListener('click', (e) => { const id = e.target.dataset.plus || e.target.dataset.minus; if (!id) return; const n = state.deck.get(id) || 0; if (e.target.dataset.plus) state.deck.set(id, n + 1); else if (n <= 1) state.deck.delete(id); else state.deck.set(id, n - 1); render(); });
  $('saved').addEventListener('click', (e) => { if (e.target.dataset.load) loadDeck(e.target.dataset.load).catch((err) => setStatus(err.message, true)); if (e.target.dataset.delete) { const saved = state.saved.find((d) => d.id === e.target.dataset.delete); deleteDeck(e.target.dataset.delete, saved ? saved.name : '该卡组').catch((err) => setStatus(err.message, true)); } });
  $('new').addEventListener('click', () => { state.editing = null; state.deck.clear(); $('deck-name').value = '我的卡组'; render(); });
  $('save').addEventListener('click', async () => { try { const cards = [...state.deck].map(([cardId, quantity]) => ({ cardId, quantity })); const method = state.editing ? 'PUT' : 'POST'; const url = state.editing ? `/api/users/demo-user/decks/${state.editing}` : '/api/users/demo-user/decks'; const d = await api(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: $('deck-name').value, faction: state.faction, cards }) }); state.editing = d.id; setStatus('保存成功'); await loadSaved(); } catch (err) { setStatus(err.message, true); } });
  loadCards().catch((err) => { $('cards').innerHTML = '<div class="empty">无法加载卡牌数据。请使用 <code>node server/index.mjs</code> 启动完整服务，而不是只启动静态预览服务器。</div>'; setStatus(err.message, true); }); loadSaved().catch((err) => setStatus(err.message, true));
})();
